---
apiVersion: v1
kind: LimitRange
metadata:
  name: project-limits
spec:
  limits:
    - max:
        cpu: 1000m
        memory: 1Gi
      min:
        cpu: 10m
        memory: 32Mi
      type: Pod
    - default:
        cpu: 200m
        memory: 128Mi
      defaultRequest:
        cpu: 200m
        memory: 128Mi
      max:
        cpu: 1000m
        memory: 1Gi
      min:
        cpu: 10m
        memory: 128Mi
      type: Container
