---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
  namespace: test
spec:
  hard:
    pods: "4" 
    requests.cpu: "1" 
    requests.memory: 1Gi 
    limits.cpu: "4"
    limits.memory: "4Gi"
    silver.storageclass.storage.k8s.io/requests.storage: "20Gi" 
    silver.storageclass.storage.k8s.io/persistentvolumeclaims: "5" 
    bronze.storageclass.storage.k8s.io/requests.storage: "0" 
    bronze.storageclass.storage.k8s.io/persistentvolumeclaims: "0" 
    requests.ephemeral-storage: 2Gi 
    limits.ephemeral-storage: 4Gi 