---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appgroup-readwrite-binding
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    name: appgroup-readwrite
